### PR TITLE
Add notification when no data is loaded

### PR DESCRIPTION
**Pull request by Free-BSG**
We added a new message when the api data is not loaded to the stores.

### CODE REVIEW

**Comment by jhcarr** [comment]
This looks like it *should* create the correct notification at the correct time but there are 2 corrections that need to happen:

1. We should be checking this information in every store. It is possible that some of our autoloads will succeed while others fail and our data will still be unusable in this case.
2. The notification can be expanded to explain that this is either a server failure or device connection failure.

**Comment by Free-BSG** [comment]
I did think of this and I added the notifications in every store and tested the app, it turned out that even when the other stores failed, only the location store would give us the notification. For some reason even if we didn't include the notification in the location store and just included it in the products and vendors, then the notification was never thrown. So I made the choice to not include extra code that didn't do anything.

Michael Freeman
________________________________

**Comment by jhcarr** [comment]
@Free-BSG 
All of this store code should be testable. I didn't see any test code in this branch - I will be working on tests to try to diagnose this problem.

**Comment by jabroderick** [comment]
This pull request is outdated, #65 is the solution we are now testing.

**Comment by Free-BSG** [comment]
Same functionality as #65, but not as clean.

**Pull request closed without merging**
