### PR TITLE
Feature4025 user documentation

### PR DESCRIPTION
**Pull request by jabroderick**
This pull request adds documentation to the app's navigation flow. This will allow users to see how to use the app if they have any questions.

### CODE REVIEW

**Comment by jabroderick** [comment]
Should this be closed for the new documentation version?

**Comment by Free-BSG** [comment]
Images for Home and List documentation are not being displayed, I think they are not referenced correctly. The .png should be .PNG. Check grammar on list page documentation. Other than that the docs look OK.

**Comment by jhcarr** [comment]
@jabroderick , eventually yes, but until we have a pull request for that content, I don't want to close this pull request as this pull request is still technically pending even if I'm pushing my recommended changes to a different branch.

**Comment by jhcarr** [comment]
This branch is redundant with #68 and will be closed

**Pull request closed without merging**
